### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by coderforlife** [sunny/all3dp#15]
Is there any documentation for the API? For example, since each item is a dictionary, are there additional params that can be sent such as scale and quantity? What formats are supported for the models (just STLs?). Are there any other endpoints?

**Comment by sunny** [comment]
As far as I know this is the only endpoint and does not provide other parameters. You should contact Craftcloud for more information about the API.

**Comment by coderforlife** [comment]
Thanks. I did contact them and there are more endpoints, but they are particular about releasing them. This one should suffice for now in any case. Thanks for documenting the only completely public one! Craftcloud themselves don't even mention this one publicly.
