### ISSUE TITLE
Requests not working

### ISSUE THREAD

**Issue by anberman** [sunny/all3dp#8]
All requests lead to 400 or 413 messages

**Comment by sunny** [comment]
Hi @anberman! The Craftcloud API works for me (at [cults3d.com](cults3d.com)), using this gem with no issues.

Did it ever work for you? `413` in HTTP is "Request Entity Too Large". Have you tried with less models?

**Comment by sunny** [comment]
Hey @anberman, any news? Did you manage to make it work?

**Comment by anberman** [comment]
Thanks! It sent the config ID. I just had a stupid typo on my end. Thanks for all the help!

**Comment by anberman** [comment]
Hello again! It seems they somewhat-recently changed their API to no longer allow the "use-model-urls" option. Do you know of any work-arounds?
